//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.23 at 01:35:41 ŒßŒã JST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.fixprotocol.org/ATDL-1-1/Layout", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.atdl4j.atdl.layout;
